### ISSUE TITLE
初次绑定使用有问题

### ISSUE THREAD

**Issue by NepPure** [monsterxcn/nonebot-plugin-gspanel#1]
面板 100xx

bot一直返回

<img width="378" alt="image" src="https://user-images.githubusercontent.com/12379907/176092462-bf6b1d4b-c5aa-488d-870a-5e4999d2f1e6.png">

这里

<img width="536" alt="image" src="https://user-images.githubusercontent.com/12379907/176093722-c63b0c77-ce20-4573-a1a2-427215875338.png">

`char=”面板“`

**Comment by NepPure** [comment]
不知道和版本有没有关系 这个写法Input包含了指令 ”面板“

<img width="569" alt="image" src="https://user-images.githubusercontent.com/12379907/176094195-e5c21b78-bf4d-4b5f-9490-42ce28aefa9b.png">


看后面代码的逻辑应该是不包含

**Comment by NepPure** [comment]
大佬考虑把伤害计算也迁移一下？

![image](https://user-images.githubusercontent.com/12379907/176147016-2f76f10d-2874-4152-9749-e93142a65551.png)

**Comment by monsterxcn** [comment]
伤害计算看着太复杂了，所以才没做的（（（

**Comment by monsterxcn** [comment]
> 不知道和版本有没有关系 这个写法Input包含了指令 ”面板“
> 
> <img alt="image" width="569" src="https://user-images.githubusercontent.com/12379907/176094195-e5c21b78-bf4d-4b5f-9490-42ce28aefa9b.png">
> 
> 看后面代码的逻辑应该是不包含
> 
> <img alt="image" width="125" src="https://user-images.githubusercontent.com/12379907/176094247-01e3c621-77b1-424c-ac5c-cb2df897b96b.png">

那看起来是 beta 版本的 `.get_plaintext()` 方法稍微变了，我这边由于是 alpha 的，这样写不包含触发的关键字。

你可以先自己 `.replace("面板", "")` 小改一下

**Comment by monsterxcn** [comment]
maybe 像这样？

```python
plain = event.get_plaintext().replace("panel", "").replace("评分", "").replace("面板", "")
input = [i for i in plain.split(" ") if i]
```

**Comment by NepPure** [comment]
嗯 我直接

`input=input[1:]`

**Comment by NepPure** [comment]
> 伤害计算看着太复杂了，所以才没做的（（（

哈哈哈
