### ISSUE TITLE
队伍伤害无法计算妮露

### ISSUE THREAD

**Issue by 63248797** [monsterxcn/nonebot-plugin-gspanel#11]
还有甘雨和草神班尼特的新融甘组合，如果能自定义操作手法应该就好了

**Comment by monsterxcn** [comment]
你有注意到图片底部的 `Data from Teyvat` 吗？如果该小程序无法查询，那么此插件也无能为力。插件仅对该小程序接口的默认返回数据进行整理。😘

如果小程序可查但此插件无法查询（含有旅行者的队伍除外），请附带日志继续反馈~

**Comment by monsterxcn** [comment]
我去试了下妮露、夜兰、珊瑚宫心海、纳西妲的队伍，可以正常返回。

所以并不是队伍伤害无法计算妮露，只是部分配队尚未支持。

请耐心等待上游接口支持，此插件不负责具体计算实现。
