### ISSUE TITLE
胡桃队伍手法错误

### ISSUE THREAD

**Issue by forchannot** [monsterxcn/nonebot-plugin-gspanel#12]
胡桃1命了计算仍然是a重跳，应该是a重冲刺，少了3次a重击
![image](https://user-images.githubusercontent.com/100580891/202901199-ea63524c-89a6-40f6-99de-35db8d22b8e9.png)

**Comment by monsterxcn** [comment]
你有注意到图片底部的 `Data from Teyvat` 吗？如果有自定义手法需求建议自行前往该小程序操作。插件仅对该小程序接口的默认返回数据进行整理。😘

如果插件跟小程序默认数据仍有较大差异，请继续反馈~
