### ISSUE TITLE
查询只有前两几次能成功，后面就报错了

### ISSUE THREAD

**Issue by Duoream** [monsterxcn/nonebot-plugin-gspanel#13]
![2a9114e6827dbb7.png](https://user-images.githubusercontent.com/50335564/202911254-08205216-9c04-4679-8cc2-4ed837e1691d.png)

**Comment by monsterxcn** [comment]
有点怪，看起来像是 nonebot_plugin_htmlrender 或者 py-plugin 那边的问题。

大概是浏览器进程被意外关闭了。正常情况的话，插件启动之后应该会有一个浏览器的常驻进程，每次图片渲染在该浏览器上新建页面。

**Comment by monsterxcn** [comment]
不太懂，渲染图片这部分是交给依赖完成的，不是由此插件完全控制。

我猜测可能的原因：浏览器进程（非 YzBot）意外崩溃？服务器内存不够？
