### ISSUE TITLE
队伍伤害数据解析出错

### ISSUE THREAD

**Issue by 63248797** [monsterxcn/nonebot-plugin-gspanel#16]
11-30 07:42:24 [ERROR] nonebot_plugin_gspanel | 队伍伤害数据解析出错 KeyError
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-HzWOmnzI-py3.10\lib\site-packages\nonebot_plugin_gspanel\data_source.py", l
ine 310, in getTeam
    data = await simplTeamDamageRes(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\littlepa
imon-HzWOmnzI-py3.10\lib\site-packages\nonebot_plugin_gspanel\data_convert.py",
line 650, in simplTeamDamageRes
    "elem": rolesData[pieData[0]["char"]]["element"],
KeyError: '原绽放伤害'

提示这个错误，大概是什么原因呢，算妮露+草神就报错

**Comment by monsterxcn** [comment]
版本太低了吧？是最新版 2.8.0 吗？理论上早在 https://github.com/monsterxcn/nonebot-plugin-gspanel/commit/80bdbc259b8c7b1582f8d8a723ec6b87c081677b 就修复了。
