### ISSUE TITLE
报错，无法正常使用

### ISSUE THREAD

**Issue by 1409109991** [monsterxcn/nonebot-plugin-gspanel#18]
![image](https://user-images.githubusercontent.com/79674967/205886420-dc1fec5d-7312-4ec6-b2cf-45d91a024ecb.png)
这是在群里问的结果
![image](https://user-images.githubusercontent.com/79674967/205886571-887ef0a0-700b-431c-8e2b-56f0b47792bd.png)

**Comment by monsterxcn** [comment]
看起来是个重复的 issue，请先参考这个 https://github.com/monsterxcn/nonebot-plugin-gspanel/issues/15#issuecomment-1328224939 填写环境变量
