### ISSUE TITLE
chromium进程未能正确关闭

### ISSUE THREAD

**Issue by NepPure** [monsterxcn/nonebot-plugin-gspanel#2]
https://github.com/monsterxcn/nonebot-plugin-gspanel/blob/5c31def535cd9434873c04e7f38170756131d252/nonebot_plugin_gspanel/html_render.py#L260-L266

这里大概需要关闭窗口，否则随着时间累计会有很多没有关闭的chromium进程

```python
res = await img2Base64(picImage)
await page.close()
```

**Comment by monsterxcn** [comment]
哦哦漏了漏了！感谢
