### ISSUE TITLE
无法发送群聊消息

### ISSUE THREAD

**Issue by Bobzheng1997** [monsterxcn/nonebot-plugin-gspanel#21]
队伍伤害的功能在私聊的时候可以正常使用，但是群聊的时候机器人无法正常发送消息；
![image](https://user-images.githubusercontent.com/54778200/208222993-7bb0e263-037a-43cf-8f2a-3bedd7f48046.png)

**Comment by monsterxcn** [comment]
py-plugin 问题，我不懂，别问我

**Comment by Bobzheng1997** [comment]
> 

哦哦，谢谢，搞错了

**Comment by githust66** [comment]
> py-plugin 问题，我不懂，别问我

![image](https://user-images.githubusercontent.com/53259654/210745147-2aa2f5f9-58f2-44ec-b01e-3fe90369072e.png)
大佬，帮忙看看这个是哪的问题哦
