### ISSUE TITLE
playwright._impl._api_types.Error: Target page, context or browser has been closed

### ISSUE THREAD

**Issue by githust66** [monsterxcn/nonebot-plugin-gspanel#23]
![image](https://user-images.githubusercontent.com/53259654/210745508-f4172cf5-ee5e-49d7-8b3a-5910caf0265f.png)
每次重启后好一下，过一段时间就报这个错了

**Comment by monsterxcn** [comment]
没太理解，重启后你什么也没干就报这个错吗？还是你发了条命令查询后报错？

**Comment by githust66** [comment]
> 没太理解，重启后你什么也没干就报这个错吗？还是你发了条命令查询后报错？
重启后发队伍伤害的命令是正常的， 过了一段时间，大概一个多小时，再发队伍伤害的命令就报这个错了，要再次重启才会好一段时间

**Comment by monsterxcn** [comment]
playwright 的问题有些玄学。你的系统是 CentOS 什么的吗？或者是什么在旧手机上跑的 Yunzai？

**Comment by githust66** [comment]
> playwright 的问题有些玄学。你的系统是 CentOS 什么的吗？或者是什么在旧手机上跑的 Yunzai？

啊这，系统是centos 7.9最新版

**Comment by monsterxcn** [comment]
那有点见怪不怪了，CentOS 下 playwright 就是毛病多。你有尝试过 https://github.com/monsterxcn/nonebot-plugin-gspanel/issues/20#issuecomment-1354701954 说的那些安装 CentOS 系统依赖再重启吗

**Comment by githust66** [comment]
> 那有点见怪不怪了，CentOS 下 playwright 就是毛病多。你有尝试过 [#20 (comment)](https://github.com/monsterxcn/nonebot-plugin-gspanel/issues/20#issuecomment-1354701954) 说的那些安装 CentOS 系统依赖再重启吗

没有，我去看看，谢谢哈
