### ISSUE TITLE
使用#队伍伤害报错

### ISSUE THREAD

**Issue by TakeyaYuki** [monsterxcn/nonebot-plugin-gspanel#24]
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/39726606/211043648-dd244fd1-a18d-485c-81e5-4b8a823d082a.png">

**Comment by monsterxcn** [comment]
同 #22 。

返回为 `{}` 即小程序繁忙，插件也无能为力。明天我会改一下返回的消息。

**Comment by TakeyaYuki** [comment]
感谢大佬回复～
