### ISSUE TITLE
精简对用户无用log

### ISSUE THREAD

**Issue by forchannot** [monsterxcn/nonebot-plugin-gspanel#26]
如题，每次更新面板控制台都要输出好上百行角色信息的json，这个log对于用户来说无关紧要，可以去除或者改为简洁的一句话表示就行。
涉及到的有圣遗物评分依据，角色数据变化等

**Comment by monsterxcn** [comment]
小问题，已经在 8b0a0bf93175ef65ea9691f48b09ff56cbda7c28 abd56fd7245954a579d1e235cf39e91c6af0d790 等 commit 中慢慢调整了，后续会再酌情调整。

不过有些日志是 DEBUG 日志，本身就是针对开发环境排查错误的，用户应该根据自己需要调整输出的日志等级。

面板上像评分这种东西比较众口难调，移植的喵版评分也并不是完全一致，有日志才好判断计算过程具体是从什么位置开始出现偏差。圣遗物评分依据我看到目前是 INFO 级别，后续会调整到 DEBUG 级别；角色数据变化我觉得放在 INFO 是很正常的，并且也只有一条，无关痛痒。

**Comment by forchannot** [comment]
> 
但是角色数据变化的json太多了
![image](https://user-images.githubusercontent.com/100580891/212523902-8d278438-c5d3-46e4-888a-7700144455b4.png)
像这样的一个角色有两三页，把info级别改成（xxx数据更新成功就行），debug级别的再输出这些日志

**Comment by monsterxcn** [comment]
行吧… 没考虑过，你这终端为什么会这样显示，实际这只是一行的内容。

![image](https://user-images.githubusercontent.com/22407052/212524102-691cd0dd-a8dd-4feb-b399-15cf344332d9.png)
