### ISSUE TITLE
支持3.0相关是不是需要更新

### ISSUE THREAD

**Issue by NepPure** [monsterxcn/nonebot-plugin-gspanel#3]
草算法之类的

**Comment by monsterxcn** [comment]
厄厄，等等看 miao-plugin 怎么处理吧，我不懂什么草算法

不过这个项目主要是圣遗物评分，不涉及伤害计算，主要还是看圣遗物词条权重之类的。

**Comment by NepPure** [comment]
😆 主要是提醒你要更新

**Comment by monsterxcn** [comment]
懒，摸完了抽卡记录的插件不想干活（（

**Comment by monsterxcn** [comment]
插件毛病有些多，打算要更新就好好改一下，一时半会应该是吃不上热乎的了（（

想做（抄）一下词条数计算或这单个词条得分之类的功能，现在这种直接一个分数感觉容易误导。但是出于排版限制和个人能力，不打算两个都做，有没有什么建议？

**Comment by NepPure** [comment]
miao plugin那个我感觉挺好的 就是太耦合了 那个直接能移植过来 感觉就可以了
