### ISSUE TITLE
KeyError: 'avatarInfoList'和KeyError: 'showAvatarInfoList'

### ISSUE THREAD

**Issue by krasus1995** [monsterxcn/nonebot-plugin-gspanel#4]

**Comment by monsterxcn** [comment]
> 在没有错误日志的情况下诊断任何问题无异于闭眼开车。

**Comment by krasus1995** [comment]
> 
我觉得也是，我用你图里的就是正常的

**Comment by monsterxcn** [comment]
那你能提供一下 `data/gspanel/cache/出错的UID__data.json` 文件大概的内容吗？

看来我判断写得不对劲，把错的数据缓存了，然后我调用缓存的时候又总是相信缓存的数据都是对的。因此目前可能需要手动删掉错误的缓存才能正常使用。

**Comment by monsterxcn** [comment]
可以删掉错误的缓存，更新插件 0.1.3 版本试试

**Comment by yjh021225** [comment]
无法生成图片怎么回事

**Comment by monsterxcn** [comment]
@krasus1995 有关 `KeyError` 的问题应该已经在 commit c2e4a3658f32c4c47c04923c65803980d1b2ef55 解决。后续若仍有此问题，可以随时 Reopen 此 issue。
