### ISSUE TITLE
功能请求：统一格式

### ISSUE THREAD

**Issue by CUZNIL** [monsterxcn/nonebot-plugin-gspanel#47]
### 功能请求

 - 需求原因：云崽用户希望能利用喵喵插件获取过的数据使用队伍伤害功能
 - 预期功能：本地面板数据缓存与[喵喵插件](https://github.com/yoimiya-kokomi/miao-plugin)生成的面板数据通用，以便云崽用户直接调用喵喵插件已经获取过的面板数据，降低enka服务压力。
 - 实现方案：与喵喵插件的用户面板数据文件采用相同的格式

### 额外信息

人比较菜，不知道还能提供什么信息。如果需要喵喵插件的用户面板数据文件样例我可以提供。

**Comment by CUZNIL** [comment]
> 为什么云崽大佬那么多，就没人改一个单纯的队伍伤害计算插件呢？

我也不理解orz

**Comment by CUZNIL** [comment]
大佬您好，我需要一点帮助，但是我找不到github在哪里可以私信，考虑到是相关内容我就在这个issue下面问了。

想请教一下，该插件生成的面板缓存文件里的`avatars[~].weapon.icon`这个字段是从哪里获取内容的？我没有找到。

请教这个是因为我在写一个[面板数据互通的插件](https://gitee.com/CUZNIL/Yunzai-MiaoToGspanel/)，目前遇到这一处暂时没法自己解决，于是就想来问一问作者。

具体来讲就是这个数据，在该插件配置的缓存目录下没有找到对应字段。尝试读了一下插件代码中的`data_updater.py` `data_source.py` `data_convert.py`，没看懂怎么搞的。

![image](https://user-images.githubusercontent.com/76582404/230731016-3e05c375-6cc8-4db7-aa5a-a07a13e07106.png)

**Comment by monsterxcn** [comment]
这是原神那边规定的，Enka 原返回里有

**Comment by CUZNIL** [comment]
> 这是原神那边规定的，Enka 原返回里有

多谢！但是请问有什么办法能通过武器id或者武器昵称去获取对应的icon字段吗？

我目前的想法是从[这个文档](https://gitlab.com/Dimbreath/AnimeGameData/-/blob/master/ExcelBinOutput/WeaponExcelConfigData.json)里获取需要的字段，再预先处理好武器id与icon字段的对应关系，最后把处理好的对应关系放进我想写的js插件内。

这样操作的话，时效性不合适，我不太可能每次游戏一更新就立刻去维护一遍插件。所以想请教一下有没有什么优雅一点的方式？

**Comment by CUZNIL** [comment]
> 你说的办法我认为就挺合适，自动更新想办法弄 GitHub Actions 跑一下。
> 
> 嫌麻烦也可以用安柏计划：
> 
> ```
> https://api.ambr.top/v2/chs/weapon
> https://api.ambr.top/v2/chs/weapon/{id}
> ```



多谢！直接这样用安柏接口摆烂貌似方便很多诶ww
