### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by mengluo04** [monsterxcn/nonebot-plugin-gspanel#68]
### 运行环境

 - 操作系统：Raspbian GNU/Linux 11 (bullseye)
 - Python 版本：3.9.2
 - NoneBot2 版本：最新
 - GsPanel 版本：最新
 - 其他环境版本：[根据报错位置自行决定是否有其他依赖版本需要说明。Yunzai-Bot & py-plugin 用户请说明相关环境。没有填无]

#### 场景

 - 触发命令：[例如 `面板` / `队伍伤害` / 其他]
 - 命令输入：[例如 `134266985` / `雷九万班@某人` / 无]
 - Bot 返回：[Bot 发送的文字消息内容 / 无]

#### 日志

```
[此处粘贴后台日志，如果不清楚报错源头请从触发报错的消息发送开始，截至报错全部结束]
```

### 额外信息

![image](https://github.com/monsterxcn/nonebot-plugin-gspanel/assets/32565940/a36f7cf6-ba9d-4474-98ab-6af5db318774)

**Comment by forchannot** [comment]
你的系统不支持安装playwright，你是arm32的系统吗，playwright在1.30之后已经支持了`manylinux: glibc 2.17+ ARM64`系列。本项目高度依赖playwright，请确保你的系统支持安装

**Comment by forchannot** [comment]
以下是目前playwright所需的系统条件，请确保你的系统在这支持范围内
```
System requirements
Node.js 18+
Windows 10+, Windows Server 2016+ or Windows Subsystem for Linux (WSL).
MacOS 12 Monterey, MacOS 13 Ventura, or MacOS 14 Sonoma.
Debian 11, Debian 12, Ubuntu 20.04 or Ubuntu 22.04, Ubuntu 24.04, on x86-64 and arm64 architecture.
```

**Comment by mengluo04** [comment]
> 你的系统不支持安装playwright，你是arm32的系统吗，playwright在1.17/1.30之后已经支持了`manylinux: glibc 2.17+ ARM64`系列。本项目高度依赖playwright，请确保你的系统支持安装

是的，它是armv71/armhf的32位版本，看起来是不支持了
