### ISSUE TITLE
【安装后不生效】

### ISSUE THREAD

**Issue by mengluo04** [monsterxcn/nonebot-plugin-gspanel#69]
### 运行环境

 - 操作系统：Ubuntu 22.04
 - Python 版本：3.10.12
 - NoneBot2 版本：最新
 - GsPanel 版本：最新
 - 其他环境版本：无

### 报错详情
接受参数没反应

#### 场景

 - 触发命令：面板、面板绑定等任意功能
 - 命令输入：面板
 - Bot 返回：无

#### 日志

![image](https://github.com/monsterxcn/nonebot-plugin-gspanel/assets/32565940/36efb79e-603c-4b04-b914-88bf291dc0fb)
root@iZ2vcdw4cft21ukahzrwqwZ:/home/software/nb-bot# nb run
Using python: /home/software/nb-bot/.venv/bin/python
06-08 19:07:49 [SUCCESS] nonebot | NoneBot is initializing...
06-08 19:07:49 [INFO] nonebot | Current Env: prod
06-08 19:07:49 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_alconna:uniseg" from "nonebot_plugin_alconna.uniseg"
06-08 19:07:49 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_waiter"
06-08 19:07:49 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_alconna"
06-08 19:07:50 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_htmlrender"
06-08 19:07:50 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_heweather"
06-08 19:07:53 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_gspanel"
06-08 19:07:53 [SUCCESS] nonebot | Running NoneBot...
06-08 19:07:53 [INFO] uvicorn | Started server process [237419]
06-08 19:07:53 [INFO] uvicorn | Waiting for application startup.
06-08 19:07:53 [INFO] nonebot_plugin_htmlrender | 使用 chromium 启动
06-08 19:07:53 [INFO] nonebot_plugin_htmlrender | Browser Started.
06-08 19:07:53 [INFO] nonebot_plugin_gspanel | 正在检查面板插件所需资源...
06-08 19:07:53 [INFO] nonebot_plugin_gspanel | 面板插件所需资源检查完毕！
06-08 19:07:53 [INFO] uvicorn | Application startup complete.
06-08 19:07:53 [INFO] uvicorn | Uvicorn running on http://0.0.0.0:23038 (Press CTRL+C to quit)
06-08 19:07:53 [INFO] uvicorn | ('127.0.0.1', 35702) - "WebSocket /onebot/v11/ws" [accepted]
06-08 19:07:53 [INFO] nonebot | OneBot V11 | Bot 2389500141 connected
06-08 19:07:53 [INFO] websockets | connection open
06-08 19:08:02 [SUCCESS] nonebot | OneBot V11 2389500141 | [message.private.friend]: Message 1415879026 from 1263041461 '面板'
06-08 19:08:04 [SUCCESS] nonebot | OneBot V11 2389500141 | [message.private.friend]: Message 1415928782 from 1263041461 'panel'

### 额外信息
1、使用pip install nb-cli
2、使用nb create创建机器人
3、使用nb plugin install nonebot-plugin-gspanel安装插件
4、使用nb run运行项目

nb plugin install nonebot-plugin-heweather 这个插件可以正常接受并返回

###配置文件
- .env.prod
DRIVER=~fastapi+~httpx+~websockets
HOST=0.0.0.0
PORT= 23038

**Comment by forchannot** [comment]
开启`LOG_LEVEL=DEBUG`后看看

**Comment by mengluo04** [comment]
> 在你的`.env.prod`里开启`LOG_LEVEL=DEBUG`后看看
这样的
![image](https://github.com/monsterxcn/nonebot-plugin-gspanel/assets/32565940/23ea682b-9dfb-4fda-83eb-f31a2126d9eb)

**Comment by forchannot** [comment]
你自己加了command start，但是你没用

**Comment by forchannot** [comment]
![image](https://github.com/monsterxcn/nonebot-plugin-gspanel/assets/100580891/62a7eeb1-4af9-4101-a548-975efeb12154)
heweather用的不受这个配置影响，本插件会受

**Comment by mengluo04** [comment]
> ![image](https://private-user-images.githubusercontent.com/100580891/337872921-62a7eeb1-4af9-4101-a548-975efeb12154.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NDg3NzQsIm5iZiI6MTcxNzg0ODQ3NCwicGF0aCI6Ii8xMDA1ODA4OTEvMzM3ODcyOTIxLTYyYTdlZWIxLTRhZjktNDEwMS1hNTQ4LTk3NWVmZWIxMjE1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQxMjA3NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDUxZmViYTk3YzcwM2FhN2I2NzBjNWJmZjBmYzIzNTc1Y2VjMWMwMDcwYTljNTY4NDc2NjRiNDAxNTQyZmQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.167Jy8oO0Eo5wufX65DWuyiMd23eJRDjEbjkvEl-4VI) heweather用的不受这个配置影响，本插件会受

这个好像是nonebot2默认的，我手动设置了一个就好了
