### ISSUE TITLE
暂时无法访问面板数据接口..

### ISSUE THREAD

**Issue by Msg-Lbo** [monsterxcn/nonebot-plugin-gspanel#8]
提示：暂时无法访问面板数据接口..
无其他报错

**Comment by monsterxcn** [comment]
仔细看一下 README

**Comment by monsterxcn** [comment]
![image](https://user-images.githubusercontent.com/22407052/192775391-3f5b0058-5162-4190-bb14-d539ff3d4873.png)

[Enka.Network](https://enka.network)

**Comment by NanakoOfficial** [comment]
我也是之前用的好好的，今晚就开始这样了，无法访问面板端口

**Comment by monsterxcn** [comment]
恼，怎么都不看我写的说明吗？上面那么大个图也看不见吗？

再 Copy 一下 README 使用须知部分：

> 插件返回「暂时无法访问面板数据接口..」可能的原因有：Bot 与 [Enka.Network](https://enka.shinshin.moe/) 的连接不稳定；[Enka.Network](https://enka.shinshin.moe/) 服务器暂时故障等。

现在这种情况也算 **[Enka.Network](https://enka.shinshin.moe/) 服务器暂时故障** 这类，上游会在每个大版本更新的时候进入维护状态，你自己去查一下就能看到我上面那个图片一样的结果，解决办法就是等上游维护完。你用其他查面板的工具基本也是一样的结果，不要反复问了，等一阵子就好了。
