### ISSUE TITLE
响应词可以更改吗

### ISSUE THREAD

**Issue by RUSSELL987** [monsterxcn/nonebot-plugin-gspanel#9]

**Comment by monsterxcn** [comment]
不可以，这是命令触发定义。

经常误触发吗？我可以做的更激进一点，只响应 `面板+角色名`，你想要的是这个吗？

**Comment by monsterxcn** [comment]
还是说你想要的是把 `面板` 前缀改成别的自定义字符串？这个我倒是没做过

**Comment by RUSSELL987** [comment]
> 还是说你想要的是把 `面板` 前缀改成别的自定义字符串？这个我倒是没做过

想改成自定义字符串来着

**Comment by monsterxcn** [comment]
**下个版本** 将支持此功能，需要参考 README.md 在 Bot 引用的 `.env` 中添加环境变量来定义你需要的前缀字符串。例如：

```
GSPANEL_ALIAS=["面板", "展柜"]
```

不过插件的 **下个版本** 还要再稍等几天。

**Comment by monsterxcn** [comment]
嘶，在琢磨另外一件事把这个插件忘记了。

暂且先发个版让你用别名吧，看来新功能还要再拖些日子。
